import streamlit as st
import streamlit.components.v1 as components
import base64

st.set_page_config(
    page_title="太鼓の達人風リズムゲーム",
    layout="centered"
)

st.title("🥁 本格派！太鼓の達人風ミニゲーム")
st.write("不具合の原因となっていた構文処理を完全に対策しました！画面内のボタンかキーボードで遊べます。")

# Pythonのトリプルクォーテーション誤認バグを100%防ぐため、1行ずつ安全な文字列として定義
html_lines = [
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    "    <meta charset='UTF-8'>",
    "    <title>Taiko Game</title>",
    "    <style>",
    "        body { background-color: #111; color: #fff; font-family: 'Helvetica Neue', Arial, sans-serif; text-align: center; margin: 0; padding: 5px; overflow: hidden; user-select: none; }",
    "        #gameContainer { position: relative; width: 100%; max-width: 800px; margin: 0 auto; }",
    "        canvas { background-color: #222; border: 3px solid #ff4b4b; border-radius: 8px; width: 100%; height: auto; }",
    "        #buttonArea { margin-top: 10px; display: flex; justify-content: center; gap: 15px; }",
    "        .drum-btn { flex: 1; max-width: 150px; padding: 12px; font-size: 16px; font-weight: bold; color: white; border: none; border-radius: 8px; cursor: pointer; box-shadow: 0 4px #333; }",
    "        .drum-btn:active { transform: translateY(4px); box-shadow: none; }",
    "        .don-btn { background-color: #ff4757; }",
    "        .ka-btn { background-color: #1e90ff; }",
    "        #instructions { margin-top: 10px; font-size: 13px; color: #aaa; }",
    "        #resultScreen { display: none; background: linear-gradient(135deg, #cc2e2e, #ff6b6b); border: 4px solid #ffd700; border-radius: 12px; width: 100%; max-width: 600px; margin: 15px auto; padding: 20px; box-shadow: 0 0 25px rgba(255, 215, 0, 0.6); }",
    "        .result-title { font-size: 28px; font-weight: bold; color: #ffd700; margin-bottom: 15px; text-shadow: 2px 2px #000; }",
    "        .result-stats { background: rgba(0, 0, 0, 0.6); border-radius: 8px; padding: 15px; font-size: 18px; text-align: left; margin-bottom: 20px; line-height: 1.8; }",
    "        .stat-line { display: flex; justify-content: space-between; border-bottom: 1px dashed #555; }",
    "        .stat-value { font-weight: bold; color: #fffa65; }",
    "        .clear-comment { font-size: 22px; font-weight: bold; color: #fff; margin-bottom: 20px; }",
    "        .retry-btn { background-color: #ffd700; color: #111; font-size: 18px; font-weight: bold; padding: 10px 30px; border: none; border-radius: 25px; cursor: pointer; box-shadow: 0 4px #b39600; }",
    "    </style>",
    "</head>",
    "<body>",
    "    <div id='gamePlayArea'>",
    "        <div id='gameContainer'>",
    "            <canvas id='gameCanvas' width='800' height='200'></canvas>",
    "        </div>",
    "        <div id='buttonArea'>",
    "            <button class='drum-btn ka-btn' onclick='triggerHit(\"ka\")'>カッ (フチ)</button>",
    "            <button class='drum-btn don-btn' onclick='triggerHit(\"don\")'>ドン (面)</button>",
    "            <button class='drum-btn don-btn' onclick='triggerHit(\"don\")'>ドン (面)</button>",
    "            <button class='drum-btn ka-btn' onclick='triggerHit(\"ka\")'>カッ (フチ)</button>",
    "        </div>",
    "        <div id='instructions'>",
    "            ※ ボタンか画面クリック、またはキーボードの <span style='background:#444;padding:2px 4px;'>D / F / J / K</span> キーでもドン・カッが打てます。",
    "        </div>",
    "    </div>",
    "    <div id='resultScreen'>",
    "        <div class='result-title'>🥁 結果発表 🥁</div>",
    "        <div id='clearComment' class='clear-comment'>演奏終了！</div>",
    "        <div class='result-stats'>",
    "            <div class='stat-line'><span>最終スコア:</span><span id='resScore' class='stat-value'>0</span></div>",
    "            <div class='stat-line'><span>最大コンボ:</span><span id='resCombo' class='stat-value'>0</span></div>",
    "            <div class='stat-line'><span>「良」の数:</span><span id='resPerfect' class='stat-value'>0</span></div>",
    "            <div class='stat-line'><span>「可」の数:</span><span id='resGood' class='stat-value'>0</span></div>",
    "            <div class='stat-line'><span>「不可」の数:</span><span id='resMiss' class="stat-value">0</span></div>",
    "        </div>",
    "        <button class='retry-btn' onclick='clickRetry()'>もう一度あそぶ</button>",
    "    </div>",
    "    <script>",
    "        const canvas = document.getElementById('gameCanvas');",
    "        const ctx = canvas.getContext('2d');",
    "        let score = 0, combo = 0, maxCombo = 0, currentFrame = 0, judgmentTimer = 0;",
    "        let countPerfect = 0, countGood = 0, countMiss = 0;",
    "        let gameActive = false, lastJudgment = '';",
    "        let notes = [];",
    "        let isFirstPlay = true;",
    "        let laneFlashTimer = 0;",
    "        let laneFlashType = '';",
    "        const TARGET_X = 150, TARGET_Y = 100, TARGET_RADIUS = 30, NOTE_SPEED = 5;",
    "        let chartData = [];",
    "        const originalChart = [",
    "            {'frame': 60, 'type': 'don'}, {'frame': 80, 'type': 'don'}, {'frame': 100, 'type': 'don'}, {'frame': 120, 'type': 'don'},",
    "            {'frame': 140, 'type': 'ka'}, {'frame': 160, 'type': 'ka'}, {'frame': 180, 'type': 'ka'}, {'frame': 200, 'type': 'ka'},",
    "            {'frame': 220, 'type': 'don'}, {'frame': 230, 'type': 'don'}, {'frame': 240, 'type': 'ka'}, {'frame': 260, 'type': 'don'},",
    "            {'frame': 280, 'type': 'ka'}, {'frame': 290, 'type': 'ka'}, {'frame': 300, 'type': 'don'}, {'frame': 320, 'type': 'don'},",
    "            {'frame': 340, 'type': 'don'}, {'frame': 360, 'type': 'ka'}, {'frame': 380, 'type': 'don'}, {'frame': 400, 'type': 'ka'},",
    "            {'frame': 420, 'type': 'don'}, {'frame': 430, 'type': 'don'}, {'frame': 440, 'type': 'don'}, {'frame': 460, 'type': 'ka'},",
    "            {'frame': 480, 'type': 'don'}, {'frame': 500, 'type': 'don'}, {'frame': 520, 'type': 'ka'}, {'frame': 540, 'type': 'ka'},",
    "            {'frame': 560, 'type': 'don'}, {'frame': 570, 'type': 'don'}, {'frame': 580, 'type': 'ka'}, {'frame': 600, 'type': 'don'},",
    "            {'frame': 640, 'type': 'don'}, {'frame': 660, 'type': 'ka'}, {'frame': 680, 'type': 'don'}, {'frame': 700, 'type': 'ka'},",
    "            {'frame': 720, 'type': 'don'}, {'frame': 730, 'type': 'don'}, {'frame': 740, 'type': 'ka'}, {'frame': 760, 'type': 'don'},",
    "            {'frame': 780, 'type': 'ka'}, {'frame': 790, 'type': 'ka'}, {'frame': 800, 'type': 'don'}, {'frame': 820, 'type': 'don'},",
    "            {'frame': 840, 'type': 'ka'}, {'frame': 860, 'type': 'ka'}, {'frame': 880, 'type': 'don'}, {'frame': 900, 'type': 'ka'},",
    "            {'frame': 920, 'type': 'don'}, {'frame': 930, 'type': 'don'}, {'frame': 940, 'type': 'ka'}, {'frame': 960, 'type': 'don'},",
    "            {'frame': 980, 'type': 'don'}, {'frame': 990, 'type': 'don'}, {'frame': 1000, 'type': 'ka'}, {'frame': 1020, 'type': 'don'},",
    "            {'frame': 1040, 'type': 'ka'}, {'frame': 1050, 'type': 'ka'}, {'frame': 1060, 'type': 'don'}, {'frame': 1080, 'type': 'ka'},",
    "            {'frame': 1100, 'type': 'don'}, {'frame': 1120, 'type': 'don'}, {'frame': 1140, 'type': 'ka'}, {'frame': 1160, 'type': 'don'},",
    "            {'frame': 1200, 'type': 'don'}, {'frame': 1210, 'type': 'don'}, {'frame': 1220, 'type': 'ka'}, {'frame': 1240, 'type': 'don'},",
    "            {'frame': 1260, 'type': 'ka'}, {'frame': 1270, 'type': 'ka'}, {'frame': 1280, 'type': 'don'}, {'frame': 1300, 'type': 'don'},",
    "            {'frame': 1320, 'type': 'don'}, {'frame': 1340, 'type': 'ka'}, {'frame': 1360, 'type': 'don'}, {'frame': 1380, 'type': 'ka'},",
    "            {'frame': 1400, 'type': 'don'}, {'frame': 1410, 'type': 'don'}, {'frame': 1420, 'type': 'don'}, {'frame': 1440, 'type': 'ka'},",
    "            {'frame': 1460, 'type': 'don'}, {'frame': 1480, 'type': 'don'}, {'frame': 1500, 'type': 'ka'}, {'frame': 1520, 'type': 'ka'},",
    "            {'frame': 1540, 'type': 'don'}, {'frame': 1550, 'type': 'don'}, {'frame': 1560, 'type': 'ka'}, {'frame': 1580, 'type': 'don'},",
    "            {'frame': 1620, 'type': 'don'}, {'frame': 1630, 'type': 'don'}, {'frame': 1640, 'type': 'don'}, {'frame': 1660, 'type': 'ka'},",
    "            {'frame': 1680, 'type': 'don'}, {'frame': 1690, 'type': 'ka'}, {'frame': 1700, 'type': 'don'}, {'frame': 1720, 'type': 'ka'},",
    "            {'frame': 1740, 'type': 'don'}, {'frame': 1750, 'type': 'don'}, {'frame': 1760, 'type': 'ka'}, {'frame': 1780, 'type': 'don'},",
    "            {'frame': 1800, 'type': 'ka'}, {'frame': 1810, 'type': 'ka'}, {'frame': 1820, 'type': 'don'}, {'frame': 1840, 'type': 'don'},",
    "            {'frame': 1860, 'type': 'don'}, {'frame': 1880, 'type': 'ka'}, {'frame': 1900, 'type': 'don'}, {'frame': 1920, 'type': 'ka'},",
    "            {'frame': 1940, 'type': 'don'}, {'frame': 1950, 'type': 'don'}, {'frame': 1960, 'type': 'don'}, {'frame': 1980, 'type': 'ka'},",
    "            {'frame': 2000, 'type': 'don'}, {'frame': 2020, 'type': 'don'}, {'frame': 2040, 'type': 'ka'}, {'frame': 2060, 'type': 'ka'},",
    "            {'frame': 2080, 'type': 'don'}, {'frame': 2090, 'type': 'don'}, {'frame': 2100, 'type': 'ka'}, {'frame': 2120, 'type': 'don'},",
    "            {'frame': 2160, 'type': 'don'}, {'frame': 2170, 'type': 'don'}, {'frame': 2180, 'type': 'don'}, {'frame': 2200, 'type': 'ka'},",
    "            {'frame': 2220, 'type': 'don'}, {'frame': 2230, 'type': 'ka'}, {'frame': 2240, 'type': 'don'}, {'frame': 2260, 'type': 'ka'},",
    "            {'frame': 2280, 'type': 'don'}, {'frame': 2290, 'type': 'don'}, {'frame': 2300, 'type': 'ka'}, {'frame': 2320, 'type': 'don'},",
    "            {'frame': 2340, 'type': 'ka'}, {'frame': 2350, 'type': 'ka'}, {'frame': 2360, 'type': 'don'}, {'frame': 2380, 'type': 'don'},",
